using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Uwn.Mvvm.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ObservablePropertyGenerator
	: GeneratorBase, IIncrementalGenerator
{
	// {0} = Namespace
	// {1} = Class name
	// {2} = Property Type name
	// {3} = Property name
	// {4} = Field name
	private const string Source = @"// <auto-generated/>

#nullable enable
namespace {0}
{{
	public partial class {1}
	{{
		public {2} {3}
		{{
			get => {4};
			set => SetField(ref {4}, value);
		}}
	}}
}}
#nullable disable
";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Find all Fields with the ObservableProperty attribute
		var fieldSymbols = context
			.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) => node is FieldDeclarationSyntax { AttributeLists.Count: > 0 },
				transform: static (ctx, _) => GetFieldSymbolIfObservableProperty(ctx))
			.Where(static symbol => symbol is not null);

		// Generate the source
		context.RegisterSourceOutput(
			fieldSymbols,
			static (context, fieldSymbol) => Execute(context, fieldSymbol!));
	}

	private static IFieldSymbol? GetFieldSymbolIfObservableProperty(GeneratorSyntaxContext context)
	{
		var fieldDeclaration = (FieldDeclarationSyntax)context.Node;
		foreach (var variable in fieldDeclaration.Declaration.Variables)
		{
			var symbol = context.SemanticModel.GetDeclaredSymbol(variable);
			if (symbol is IFieldSymbol fieldSymbol)
			{
				if (fieldSymbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == StringValues.ObservablePropertyAttributeFullyQualifiedName))
					return fieldSymbol;
			}
		}
		return null;
	}

	private static void Execute(SourceProductionContext context, IFieldSymbol fieldSymbol)
	{
		var location = fieldSymbol.Locations.FirstOrDefault() ?? Location.None;

		var propertyName = BuildPropertyName(fieldSymbol);
		if (propertyName is null)
		{
			context.ReportDiagnostic(StringValues.ObservablePropertyGeneratorIdPrefix, 1, DiagnosticSeverity.Error, location, StringValues.ObservablePropertyGeneratorName, "Could not build property name for '{0}'.", fieldSymbol.Name);
			return;
		}

		// {0} = Namespace
		// {1} = Class name
		// {2} = Property Type name
		// {3} = Property name
		// {4} = Field name
		var source = string.Format(Source, fieldSymbol.ContainingNamespace.ToDisplayString(), fieldSymbol.ContainingType.Name, fieldSymbol.Type.ToDisplayString(), propertyName, fieldSymbol.Name);
		var filename = BuildFilename(fieldSymbol.ContainingNamespace, fieldSymbol.ContainingType, fieldSymbol);
		context.AddSource(filename, SourceText.From(source, Encoding.UTF8));

		// Removed the report to decrease spam in the output
		//context.ReportDiagnostic(StringValues.ObservablePropertyGeneratorIdPrefix, 2, DiagnosticSeverity.Info, location, StringValues.ObservablePropertyGeneratorName, "Generated property '{0}'.", propertyName);
	}
}
