name: Build and Sign

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Decode and save .snk file
      shell: pwsh
      run: |
        $base64String = "${{ secrets.SNK_KEY_BASE64 }}"
        $bytes = [System.Convert]::FromBase64String($base64String)
        [System.IO.File]::WriteAllBytes("Assets/UWN-GH.snk", $bytes)

    - name: Build and sign the project
      run: dotnet build -c Release

    - name: Remove the .snk file
      run: rm -f Assets/UWN-GH.snk
      shell: bash
